---
title: "Exploratory lit review analysis"
author: "Lyndon Estes"
output: 
  html_document:
    toc: yes
---

## Initial analyis of metadata

### Data
```{r}
library(data.table)
library(raster)
library(sp)
require(splancs)
p_root <- lmisc::full_path(lmisc::proj_root("lit_review"), "lit_review")
p_dat <- lmisc::full_path(p_root, "data/")
dat <- read.csv("data/metadata_lde.csv", skip = 1, stringsAsFactors = FALSE)

```

### Test plots
```{r}
unique(dat$DOI.title)  # 20
unlist(strsplit(unique(dat$DOI_data_source), ";"))  # 12 more
with(dat, plot(log(plot_res), n_sites))
with(dat, plot(plot_res, n_sites, pch = 16))
with(dat, plot(plot_res, log(sampled_area), pch = 16))
with(dat, plot(log10(plot_res), log10(sampled_area), pch = 16))
with(dat, plot(log10(plot_res), log10(n_sites), pch = 16))
with(dat, plot(log10(plot_res), n_sites, pch = 16))
with(dat, plot(log(samp_duration), log(t_btwn_samp + 0.00001), pch = 16))
with(dat, plot(log(samp_duration), log(study_duration), pch = 16))
with(dat, plot(log10(t_btwn_samp + 0.00001), log10(study_duration), pch = 16))
with(dat, plot(log10(t_btwn_samp + 0.00001), log10(study_span), pch = 16))

hist(dat$t_btwn_samp + (1 / (60 * 60 * 24)))
hist(log(dat$study_duration))
hist(dat$study_span)
table(dat$study_type)
```

## Spatal and temporal data 

### Scaling in log10 space
```{r}
i <- 0.000001
j <- rep(0, 15)
for(k in 1:length(j)) {
  i <- i * 10
  j[k] <- i
}
tdt <- data.table("scaleval" = j, "time" = j)
# tdt <- data.table("scale" = c("1 msec", "1 sec", "1 min", "1 hr", "1 dy", 
#                               "1 wk", "1 mth", "1 yr", "1 de", " 1 ce"),
#                   "time" = c(1 / (1000 * 60 * 60 * 24), 1 / (60 * 60 * 24), 
#                              1 / (60 * 24), 1 / 24, 1, 7, 30, 365, 365 * 10, 
#                              365 * 100))
tdt[, tlog := log10(time)]

# i <- 0.0001
# j <- rep(0, 10)
# for(k in 1:length(j)) {
#   i <- i * 10
#   j[k] <- i
# }
rdt <- data.table("scaleval" = j, "area" = j^2)
# rdt <- data.table("scale" = c("0.000001m", "0.00001m", "0.0001m", "0.001m", 
#                               "0.01 m", "0.1 m", "1 m", "10 m", "100 m", 
#                               "1000 m", "10000 m", "100000 m"),
#                   "scaleval" = j, "area" = j^2)
#c(1/10000^2, 1/1000^2, 1/100^2, 0.1^2, 1, 10^2, 
                             #100^2, 1000^2, 10000^2, 100000^2))
rdt[, slog := log10(scaleval)]
rdt[, rlog := log10(area)]

# i <- 0.000001
# j <- rep(0, 16)
# for(k in 1:length(j)) {
#   i <- i * 10
#   j[k] <- i
# }
adt <- data.table("area" = j)
# adt <- data.table("scale" = c("<0.1 ha", "0.1 ha", "1 ha", "10 ha", "100 ha",
#                               "1000 ha", "10000 ha", "100000 ha", "1000000 ha", 
#                               "10000000 ha", "100000000 ha", "1000000000 ha"),
#                   "area" = j)
#                     c(0.1, 1, 10, 100, 1000, 10000, 100000, 1000000, 
#                               10000000, 100000000, 1000000000))
adt[, alog := log10(area)]
```

### Rasterize and calculate kernel densities

1. For spatial versus temporal version
```{r,eval = FALSE}
# raster for resolution (x dimension) versus area (y dimension)
# arst <- raster(xmn = -6, xmx = 9, ymn = -5, ymx = 10)
arst <- raster(xmn = -5, xmx = 10, ymn = -5, ymx = 10)
res(arst) <- 0.25
arst@crs <- CRS("")
arst[] <- 1
as(extent(arst), "SpatialPolygons")
spatdat <- data.table("x" = log10(dat$plot_res), "y" = log10(dat$sampled_area))
spatdat[y < -5, y := -4.5]
spatdat$n <- rep(1, nrow(spatdat))
coordinates(spatdat) <- ~x + y
plot(spatdat$x, spatdat$y)

# trst <- raster(xmn = -6, xmx = 4, ymn = -5, ymx = 5)
trst <- raster(xmn = -5, xmx = 10, ymn = -5, ymx = 10)
res(trst) <- 0.25
trst@crs <- CRS("")
trst[] <- 1

# tempdat <- data.table("x" = log10(dat$t_btwn_samp + 0.001), 
#                       "y" = log10(dat$study_duration + 0.001)) 
tempdat <- data.table("x" = log10(dat$t_btwn_samp + 0.001), 
                      "y" = log10(dat$study_span + 0.001)) 
tempdat[x < -5, x := -4.5]
tempdat[y < -5, y := -4.5]
tempdat$n <- rep(1, nrow(tempdat))
coordinates(tempdat) <- ~x + y
plot(tempdat$x, tempdat$y)

# set-up grid topologies
# sgrd <- GridTopology(cellcentre.offset = c(-5.75, -4.75), 
#                      cellsize = c(0.5, 0.5), cells.dim = c(30, 30))
# tgrd <- GridTopology(cellcentre.offset = c(-6 + (0.333 / 2), -5 + (0.333 / 2)), 
#                      cellsize = c(0.333, 0.333), cells.dim = c(30, 30))
sgrd <- tgrd <- GridTopology(cellcentre.offset = c(-4.875, -4.875), 
                             cellsize = c(0.25, 0.25), cells.dim = c(60, 60))

# kernel densities
# spatial
ppoly <- as(extent(arst), "SpatialPolygons")
crds <- slot(slot(slot(ppoly, "polygons")[[1]], "Polygons")[[1]], "coords") 
kern1 <- spkernel2d(spatdat, crds, h0 = 1.25, sgrd)
kgrid1 <- as(SpatialGridDataFrame(sgrd, data = data.frame(kern1)),
             "SpatialPixelsDataFrame")

# temporal
ppoly <- as(extent(trst), "SpatialPolygons")
crds <- slot(slot(slot(ppoly, "polygons")[[1]], "Polygons")[[1]], "coords") 
# kern2 <- spkernel2d(tempdat, crds, h0 = 1.34, tgrd)
kern2 <- spkernel2d(tempdat, crds, h0 = 1.25, tgrd)
kgrid2 <- SpatialGridDataFrame(tgrd, data = data.frame(kern2))


# rasterize
# space
sr <- raster(kgrid1)
# sr <- shift(sr, 0.125, 0.125)  # shift to line up with point offset
sr[is.na(sr)] <- 0
# time
tr <- raster(kgrid2)
# tr <- shift(tr, 0.125, 0.125)  # shift to line up with point offset
# tr <- shift(tr, 0.333 / 2, 0.333 / 2)
tr[is.na(tr)] <- 0

# have a look
plot(sr)
points(spatdat$x, spatdat$y)
plot(tr)
points(tempdat$x, tempdat$y)

# shift rasters to common axis (0-15 in x, y)
# rr <- raster(nrow = 10, ncol = 10)
# srs <- raster(extent(c(0, 15, 0, 15)))
# res(srs) <- 0.5
# srs[] <- values(sr)
# trs <- raster(extent(c(0, 15, 0, 15)))
# res(trs) <- 0.5
# trs[] <- values(tr)
# trs <- resample(trs, srs)
srs <- sr
trs <- tr
```

#### Convert to rgb space and plot
```{r, eval = FALSE}
plot(srs, axes = FALSE, box = FALSE)
plot(trs, axes = FALSE, box = FALSE)

hstretch <- function(x, brange = 0.15) return(brange + (x * (1 - brange) / 1))
srsv <- values(srs)
srsvn <- (srsv - min(srsv)) / diff(range(srsv))
srsvn[srsvn > 0] <- hstretch(srsvn[srsvn > 0])  # compress range in non-0
trsv <- values(trs)
trsvn <- (trsv - min(trsv)) / (diff(range(trsv)))
trsvn[trsvn > 0] <- hstretch(trsvn[trsvn > 0])  # compress range in non-0
hist(trsvn)
grsv <- rep(0, length(srsv))
# grsv[which(srsv 0 & trsv == 0)] <- 1
# trsvn[which(srsv == 0 & trsv == 0)] <- 1
# srsvn[which(srsv == 0 & trsv == 0)] <- 1
srtrvals <- rgb(red = srsvn, blue = trsvn, green = grsv)
z <- matrix(srtrvals, nrow=nrow(srs), ncol=ncol(srs), byrow = TRUE)
bb <- as.vector(t(bbox(srs)))

cx <- 1.2
png("paper/figures/spacevtime.png", width = 700, height = 700)
par(mar = c(3, 3, 3, 3))
plot(-5:10, -5:10, axes = F, pch = "", xlab = "", ylab = "")
rasterImage(z, bb[1], bb[3], bb[2], bb[4])
#axis(1, labels = FALSE, line = -0.5)
axis(1, at = -5:10, labels = c(rdt[, slog], 10), line = -1.6, 
     col.axis = "red", col = "red", col.ticks = "red")
axis(2, at = -5:10, labels = c(adt[, alog], 10), line = -1.6, 
     col.axis = "red", col = "red", col.ticks = "red", las = 2)
axis(3, at = -5:10, labels = c(tdt[, tlog], 10), line = -1.6, 
     col.axis = "blue", col = "blue", col.ticks = "blue")
axis(4, at = -5:10, labels = c(tdt[, tlog], 10), line = -1.6, 
     col.axis = "blue", col = "blue", col.ticks = "blue", las = 2)
mtext("Plot resolution log10(m)", side = 1, line = 1, col = "red", cex = cx)
mtext("Sampled area log10(ha)", side = 2, line = 1, col = "red", cex = cx)
mtext("Sampling interval log10(days)", side = 3, line = 1, col = "blue", 
      cex = cx)
text(16, y = 7.5, "Sampling duration log10(days)", col = "blue", srt = 270, 
     xpd = TRUE, cex = cx)
dev.off()

```

2. For resolution versus extent version
```{r,eval = FALSE}
# raster for resolution (x dimension) versus area (y dimension)
# arst <- raster(xmn = -6, xmx = 9, ymn = -5, ymx = 10)
rst <- raster(xmn = -5, xmx = 10, ymn = -5, ymx = 10)
res(rst) <- 0.25
# rst@crs <- CRS("")
rst[] <- 1
rst2 <- raster(xmn = 0, xmx = 10, ymn = 0, ymx = 10)
res(rst2) <- c(0.25, 0.25)
# rst@crs <- CRS("")
rst2[] <- 1
plot(rst2)


resdat <- data.table("x" = log10(dat$t_btwn_samp + 0.00001), 
                     y = log10(dat$plot_res))
resdat[x < -5, x := -4.5]
resdat[y < -5, y := -4.5]
resdat$n <- rep(1, nrow(resdat))
coordinates(resdat) <- ~x + y
plot(resdat$x, resdat$y)

# extdat <- data.table("x" = log10(dat$study_duration + 0.00001), 
#                       "y" = log10(dat$sampled_area)) 
extdat <- data.table("x" = log10(dat$study_span), 
                     "y" = log10(dat$sampled_area)) 
extdat[x < 0, x := 0]
extdat[y < 0, y := 0]  # setting minima to 1 day and 1 ha
extdat$n <- rep(1, nrow(extdat))
coordinates(extdat) <- ~x + y
plot(extdat$x, extdat$y)

# set-up grid topologies
sgrd <- GridTopology(cellcentre.offset = c(-4.875, -4.875), 
                     cellsize = c(0.25, 0.25), cells.dim = c(60, 60))
tgrd <- GridTopology(cellcentre.offset = c(0.125, 0.125), 
                     cellsize = c(0.25, 0.25), cells.dim = c(40, 40))
# seq(0, 10, 10 / 59)

# kernel densities
# resolution
ppoly <- as(extent(rst), "SpatialPolygons")
crds <- slot(slot(slot(ppoly, "polygons")[[1]], "Polygons")[[1]], "coords") 
kern1 <- spkernel2d(resdat, crds, h0 = 1, sgrd)
kgrid1 <- as(SpatialGridDataFrame(sgrd, data = data.frame(kern1)),
             "SpatialPixelsDataFrame")

# extent
ppoly <- as(extent(rst2), "SpatialPolygons")
crds <- slot(slot(slot(ppoly, "polygons")[[1]], "Polygons")[[1]], "coords") 
kern2 <- spkernel2d(extdat, crds, h0 = 1, tgrd)
kgrid2 <- SpatialGridDataFrame(tgrd, data = data.frame(kern2))

# rasterize
# space
rr <- raster(kgrid1)
rr[is.na(rr)] <- 0
# time
er <- raster(kgrid2)
er[is.na(er)] <- 0

# have a look
par(mfrow = c(2, 1))
plot(er)
points(extdat$x, extdat$y)
plot(rr)
points(resdat$x, resdat$y)

ers <- er
rrs <- rr
```

### Convert to rgb space and plot
```{r, eval = FALSE}
# As separate plots
png("paper/figures/res&extent.png", width = 900, height = 450)
par(mfrow = c(1, 2), oma = c(0, 0, 0, 0), mar = c(4, 4, 4, 4))
plot(rrs, xlim = c(-5, 15), ylim = c(-5, 15), 
     xlab = "Sample interval - log10(days)", 
     ylab = "Plot resolution - log10(m^2)")
plot(ers, box = FALSE, xlim = c(-5, 15), ylim = c(-5, 15), 
     xlab = "Study duration - log10(days)", ylab = "Sampled area - log10(ha)")
dev.off()

rrs2 <- rrs
# rrs2[rrs2 == 0] <- NA
ers2 <- ers
# ers2[ers2 == 0] <- NA
tcols <- rev(terrain.colors(100))
# tcols <- colorRampPalette(c("grey95", "orange", "orange", "yellow", "green"))(100)
# tcols[1] <- "grey"
png("paper/figures/res&extent_pres.png", width = 900, height = 450)
par(mfrow = c(1, 2), oma = c(0, 0, 0, 0), mar = c(5, 5, 4, 4), bg = "transparent")
plot(rrs2, xlim = c(-5, 15), ylim = c(-5, 15), 
     cex.lab = 2, col = tcols, col.lab = "white", 
     col.ticks = "white", col.axis = "white", cex.axis = 2,
     xlab = "Sample interval - log10(days)", 
     ylab = "Plot resolution - log10(m^2)")
plot(ers2, xlim = c(-5, 15), ylim = c(-5, 15), col.axis = "white", 
     cex.axis = 2, cex.lab = 2, col = tcols, col.lab = "white",
     xlab = "Study period - log10(days)", box = FALSE, col.ticks = "white", 
     ylab = "Study extent - log10(ha)")
dev.off()



# Switched off because need to reconcile scales first

# hstretch <- function(x, brange = 0.25) return(brange + (x * (1 - brange) / 1))
# ersv <- values(ers)
# ersvn <- (ersv - min(ersv)) / diff(range(ersv))
# ersvn[ersvn > 0] <- hstretch(ersvn[ersvn > 0])  # compress range in non-0
# rrsv <- values(rrs)
# rrsvn <- (rrsv - min(rrsv)) / (diff(range(rrsv)))
# rrsvn[rrsvn > 0] <- hstretch(rrsvn[rrsvn > 0])  # compress range in non-0
# hist(rrsvn)
# grsv <- rep(0, length(rrsv))
# # grsv[which(srsv 0 & trsv == 0)] <- 1
# # trsvn[which(srsv == 0 & trsv == 0)] <- 1
# # srsvn[which(srsv == 0 & trsv == 0)] <- 1
# ertrvals <- rgb(red = ersvn, blue = rrsvn, green = grsv)
# z <- matrix(ertrvals, nrow=nrow(rrs), ncol=ncol(rrs), byrow = TRUE)
# bb <- as.vector(t(bbox(rrs)))

cx <- 1.2
png("paper/figures/resvextent.png", width = 700, height = 700)
par(mar = c(3, 3, 3, 3))
plot(-5:10, -5:10, axes = F, pch = "", xlab = "", ylab = "")
rasterImage(z, bb[1], bb[3], bb[2], bb[4])
#axis(1, labels = FALSE, line = -0.5)
axis(1, at = -5:10, labels = c(rdt[, slog], 10), line = -1.6)
axis(2, at = -5:10, labels = c(adt[, alog], 10), line = -1.6)
mtext("Sample interval - log10(days)", side = 1, line = 0.8, col = "blue", 
      cex = cx)
mtext("Study duration - log10(days)", side = 1, line = 2, col = "red", cex = cx)
mtext("Plot resolution - log10(m^2)", side = 2, line = 0.8, col = "blue", 
      cex = cx)
mtext("Sampled area - log10(ha)", side = 2, line = 2, col = "red", cex = cx)
dev.off()

```
