---
title: "Main Analyses - Figure 3"
output: 
  rmarkdown::html_vignette:
    toc: yes
    number_sections: true
    toc_depth: 3
vignette: >
  %\VignetteIndexEntry{Main Analyses - Figure 3}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = 'center', fig.height = 4, 
                      fig.width = 5, cache = TRUE)
```


# Overview

The resampled full dataset created in the [Data Pre-processing vignette](data-pre-process.html) is used to construct kernel density estimates showing varying 2-D contrasts of observational scale dimensions.

# Analyses
## Data and libraries

```{r, message = FALSE, warning=FALSE}
library(ecoscales)
library(viridis)
library(lmisc)
data("dimbreaks")
data("bootperturb")
```

### Figure 3
Actual versus effective duration/extent
```{r, eval=FALSE}

# plot params
ex <- range(aaxis2$logarea)
ey <- range(aaxis2$logarea)
ll <- 3.5
cxa = 0.7
stps <- sapply(c(3, 4), function(x) which(kdat$st == x))  # IDs rs/auto/paleo
pchs <- list(1, "+")
cexs <- c(0.4, 0.6)
cuts <- 40
bump <- 3
cols <- inferno(cuts + bump)[-c(2:(bump + 1))]

# Difference in effective versus actual extent/duration against actual ext/dur
hdat_bs2 <- lapply(1:length(bootperturb), function(x) {  # x <- 1
  print(x)
  DT <- bootperturb[[x]]
  
  # extent measures log10 transformed
  edb <- DT[, lapply(.SD, log10), .SDcol = c("eff_ext", "act_ext")]
  setnames(edb, c("eff_ext", "act_ext"), c("eext", "aext"))
  edb[, dif := eext - aext]  # difference between extent and actual extent

  # duration measures log10 transformed, unreplicated dropped
  tdb <- DT[t_btwn_samp != 365 * 10000, lapply(.SD, log10), 
            .SDcol = c("eff_dur", "act_dur")]
  setnames(tdb, c("eff_dur", "act_dur"), c("edur", "adur"))
  # print(paste(edb[, .N], tdb[, .N]))
  tdb[, dif := edur - adur]  # difference between duration and actual duration
  return(list("edb" = edb, "tdb" = tdb, #"elm" = elm, "tlm" = tlm, 
              "Ns" = c(edb[, .N], tdb[, .N])))
})

# calculate box statistics
# Extent differences
eint <- aaxis2$logarea
edif_int <- rbindlist(lapply(hdat_bs2, function(y) {  # y <- hdat_bs2[[2]]
  dd <- copy(y$edb[!is.na(aext)])
  dd[aext < ex[1], aext := ex[1]]  # set to min
  # dd[eext < ex[1], eext := ex[1]]  # set to min
  dd[, int := findInterval(aext, eint, rightmost.closed = TRUE)]
  # dd[, int := findInterval(eext, eint, rightmost.closed = TRUE)]
}))
ints <- sort(edif_int[, unique(int)])
ebox <- lapply(ints, function(x) edif_int[int == x, lmisc::box_stats(dif)])
pctobs <- sapply(ints, function(x) edif_int[int == x, .N])
ewgt <- pctobs / sum(pctobs)
# round(cumsum(ewgt), 2)
ewgtint <- c(0, 1, 5, 10, 15, 20, 25) / 100  # weight intervals
ewgttxt <- c("  0", "  1", "  5", seq(10, 25, 5))
ecols <- findInterval(ewgt, ewgtint)  # corresponding color index

# temporal differences
dint <- taxis2$logdays[-5]
tx <- range(dint)
ddif_int <- rbindlist(lapply(hdat_bs2, function(y) {  # y <- hdat_bs2[[2]]
  dd <- copy(y$tdb[!is.na(adur)])
  dd[adur < tx[1], adur := tx[1]]  # set to min
  dd[adur > tx[2], adur := tx[2]]  # set to max
  dd[, int := findInterval(adur, dint, rightmost.closed = TRUE)]  # include high
  # dd[, int := findInterval(edur, dint, rightmost.closed = TRUE)]  # include high
}))
dints <- sort(ddif_int[, unique(int)])
tbox <- lapply(dints, function(x) ddif_int[int == x, lmisc::box_stats(dif)])
pctobs <- sapply(dints, function(x) ddif_int[int == x, .N])
dwgt <- pctobs / sum(pctobs)
# round(cumsum(dwgt), 2)

dwgtint <- c(0, 1, 5, 10, 15, 20, 25, 30) / 100  # weight intervals
dwgttxt <- c("  0", "  1", "  5", seq(10, 30, 5))
dcols <- findInterval(dwgt, dwgtint)  

# y grid line function
ylines <- function(yr, by, lty = 1, col = "grey") {
  abline(h = seq.int(from = yr[1], to = yr[2], by = 2), lty = lty, col = col)
}

# pdf("paper/figures/act_v_eff_diff.pdf", width = 7, height = 4)
png("vignettes/figures/fig3.png", width = 7, height = 4, res = 600, 
    units = "in")
par(mfrow = c(1, 2), mar = c(4, 0, 1, 0.75), oma = c(0, 3, 0, 0))
bx <- rowMeans(cbind(eint[-length(eint)], eint[-1]))
# cols <- sapply(ealphs, function(x) rgb(0, 0.1, 1, alpha = x))
cols <- brewer.pal(length(ewgtint) - 1, "Blues")
plot(ex, c(0, 14), pch = "", xlab = "", ylab = "", xaxt = "n", yaxt = "n",
     mgp = c(3, 0.5, 0), tcl = -0.2, xaxs = "i")
polygon(c(ex, rev(ex), ex[1]), c(-1, -1, 15, 15, -1), col = "grey90")
ylines(yr = c(0, 14), by = 2, col = "grey95")
for(i in 1:length(ebox)) {
  boxplot_v(bx[i], y = ebox[[i]], n = 1.75, whiskhgt = 1.5, 
            bfill = cols[ecols][i])
  text(bx[i], ebox[[i]][5] + 0.15, round(ewgt[i] * 100, 1), cex = 0.3)
} 
axis(1, at = eint, labels = alab2, las = 2, tcl = -0.2, cex.axis = cxa, 
     mgp = c(3, 0.5, 0))
axis(2, at = seq(0, 14, 2), las = 2, tcl = -0.2, cex.axis = cxa, 
     mgp = c(3, 0.5, 0))
mtext("Actual Extent", side = 1, line = 3, cex = 0.9)
mtext("Magnitude of difference between Extent/Duration", side = 2, line = 2.2, 
      cex = 0.9)
mtext("and Actual Extent/Duration", side = 2, line = 1.4, cex = 0.9)
lrng <- c(mean(ex), max(ex) - 0.05 * max(ex))
xs <- seq(lrng[1], lrng[2], by = (diff(lrng)) / (length(cols)))
rect_shade(xs, y = c(11.5, 12.5), fillcol = cols, linecol = "grey30")
text(xs, rep(10.5, length(xs)), ewgttxt, srt = 90, col = "grey30")
text(mean(xs), 13, "% of observations", col = "grey30")
mtext("A", side = 3, line = -1, cex = 1, adj = 0.02)

# duration
bx <- rowMeans(cbind(dint[-length(dint)], dint[-1]))
bd <- abs(dint[-length(dint)] - dint[-1])
cols <- brewer.pal(length(dwgtint) - 1, "Reds")
plot(tx, c(0, 14), pch = "", xlab = "", ylab = "", xaxt = "n", xaxs = "i",
     mgp = c(3, 0.5, 0), tcl = -0.2, yaxt = "n")
polygon(c(tx, rev(tx), tx[1]), c(-1, -1, 15, 15, -1), col = "grey90")
ylines(yr = c(0, 14), by = 2, col = "grey95")
for(i in 1:length(tbox)) {
  boxplot_v(bx[i], y = tbox[[i]], n = 0.9, inhgt = bd[i] * 10, whiskhgt = 0.75, 
            bfill = cols[dcols][i])
  text(bx[i], tbox[[i]][5] + 0.15, round(dwgt[i] * 100, 1), cex = 0.3)

} 
axis(1, at = dint, labels = tlab2[-c(5)], las = 2, tcl = -0.2, cex.axis = cxa, 
     mgp = c(3, 0.5, 0))
axis(2, at = seq(0, 14, 2), labels = rep("", 8), las = 2, tcl = -0.2, 
     cex.axis = cxa, mgp = c(3, 0.5, 0))
mtext("Actual Duration", side = 1, line = 3, cex = 0.9)
lrng <- c(mean(tx), max(tx) - 0.05 * max(tx))
xs <- seq(lrng[1], lrng[2], by = (diff(lrng)) / (length(cols)))
rect_shade(xs, y = c(11.5, 12.5), fillcol = cols, linecol = "grey30")
text(xs, rep(10.5, length(xs)), dwgttxt, srt = 90, col = "grey30")
text(mean(xs), 13, "% of observations", col = "grey30")
mtext("B", side = 3, line = -1, cex = 1, adj = 0.02)
dev.off()

```